# Generated by Django 3.1 on 2020-10-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201029_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mypost',
            field=models.TextField(null=True, verbose_name='mypost'),
        ),
    ]
