# Generated by Django 3.1 on 2020-10-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20201029_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mypost',
        ),
    ]
