# Generated by Django 3.1 on 2020-10-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201029_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myposts',
            field=models.ManyToManyField(related_name='myposts', to='network.Posts'),
        ),
    ]
