# Generated by Django 3.1 on 2020-10-29 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20201029_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='likesuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
