# Generated by Django 3.1 on 2020-10-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20201029_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myposts',
        ),
    ]
