# Generated by Django 3.1 on 2020-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_user_myposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myposts',
            field=models.ManyToManyField(blank=True, default='', related_name='myposts', to='network.Posts'),
        ),
    ]
