# Generated by Django 3.1 on 2020-12-21 14:23

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('social_security_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('admission', models.DateField(auto_now_add=True)),
                ('room_bed', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramedCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('progamed_time', models.DateField()),
                ('reponse_time', models.DateField(auto_now=True)),
                ('programed_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programed_call', to='nursing.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_id', models.CharField(max_length=25)),
                ('medical_record_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/medicalrecords'), upload_to='')),
                ('short_diagnosis', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='nursing.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EventualCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('call_time', models.DateField(auto_now_add=True)),
                ('response_time', models.DateField(auto_now=True)),
                ('eventual_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventual_call', to='nursing.patient')),
            ],
        ),
    ]
