# Generated by Django 3.1 on 2020-12-21 15:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0002_eventualcall_medicalrecord_patient_programedcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_record_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='medicalrecords'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='programedcall',
            name='progamed_time',
            field=models.DateTimeField(),
        ),
    ]
