# Generated by Django 3.1 on 2020-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0003_auto_20201221_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventualcall',
            name='call_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventualcall',
            name='response_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programedcall',
            name='reponse_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
