# Generated by Django 3.1 on 2020-12-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0004_auto_20201221_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programedcall',
            old_name='progamed_time',
            new_name='programed_time',
        ),
        migrations.RenameField(
            model_name='programedcall',
            old_name='reponse_time',
            new_name='response_time',
        ),
    ]
