# Generated by Django 3.1 on 2020-12-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0005_auto_20201221_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call', to='nursing.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('programed_time', models.DateTimeField()),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('programed_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programed_task', to='nursing.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='programedcall',
            name='programed_call',
        ),
        migrations.DeleteModel(
            name='EventualCall',
        ),
        migrations.DeleteModel(
            name='ProgramedCall',
        ),
    ]
